-- +goose Up
ALTER TABLE invitations
  DROP COLUMN is_accepted,
  ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN role ENUM('ROLE_OWNER','ROLE_ADMIN','ROLE_EDITOR','ROLE_SPECTATOR') NOT NULL DEFAULT 'ROLE_SPECTATOR';

-- +goose Down
ALTER TABLE invitations
  DROP COLUMN status,
  DROP COLUMN role,
  ADD COLUMN is_accepted BOOLEAN DEFAULT FALSE;